import { TTranscriptInstance } from "./types";

export const TEMPTRANSCRIPT: TTranscriptInstance[] = [
  {
    messageId: 1,
    time: new Date("2024-11-30T14:35:00"),
    speaker: "caller",
    text: "Hello, I need help! There's a fire in my building!",
    type: "message",
  },
  {
    messageId: 2,
    time: new Date("2024-11-30T14:35:05"),
    speaker: "dispatcher",
    text: "Can you confirm your address, please?",
    type: "message",
  },
  {
    messageId: 3,
    time: new Date("2024-11-30T14:35:08"),
    speaker: null,
    text: "Yelling in the background",
    type: "event",
  },
  {
    messageId: 4,
    time: new Date("2024-11-30T14:35:10"),
    speaker: "caller",
    text: "Yes, it's 123 Elm Street, Apartment 4B, New York, NY.",
    type: "message",
  },
  {
    messageId: 5,
    time: new Date("2024-11-30T14:35:15"),
    speaker: "dispatcher",
    text: "Got it. Is everyone out of the building?",
    type: "message",
  },
  {
    messageId: 6,
    time: new Date("2024-11-30T14:35:18"),
    speaker: null,
    text: "Fire crackling noise detected",
    type: "event",
  },
  {
    messageId: 7,
    time: new Date("2024-11-30T14:35:20"),
    speaker: "caller",
    text: "No, I can still hear people yelling upstairs.",
    type: "message",
  },
  {
    messageId: 8,
    time: new Date("2024-11-30T14:35:25"),
    speaker: "dispatcher",
    text: "Stay calm. Help is on the way. Are you in a safe location?",
    type: "message",
  },
  {
    messageId: 9,
    time: new Date("2024-11-30T14:35:30"),
    speaker: "caller",
    text: "Yes, I'm outside now, but there's so much smoke!",
    type: "message",
  },
  {
    messageId: 10,
    time: new Date("2024-11-30T14:35:35"),
    speaker: "dispatcher",
    text: "Good. Stay clear of the building. Firefighters will be there shortly. Do you see flames or just smoke?",
    type: "message",
  },
  {
    messageId: 11,
    time: new Date("2024-11-30T14:35:38"),
    speaker: null,
    text: "Sound of glass breaking detected",
    type: "event",
  },
  {
    messageId: 12,
    time: new Date("2024-11-30T14:35:40"),
    speaker: "caller",
    text: "I see flames coming from the second floor. It’s spreading fast!",
    type: "message",
  },
  {
    messageId: 13,
    time: new Date("2024-11-30T14:35:45"),
    speaker: "dispatcher",
    text: "Understood. Are you aware of anyone else who might still be inside, or do you have any information about who lives on the second floor?",
    type: "message",
  },
  {
    messageId: 14,
    time: new Date("2024-11-30T14:35:50"),
    speaker: "caller",
    text: "Yes, there's an elderly couple who live in Apartment 2A. They may not have made it out.",
    type: "message",
  },
  {
    messageId: 15,
    time: new Date("2024-11-30T14:35:55"),
    speaker: "dispatcher",
    text: "Thank you for letting us know. We’ll relay this to the fire department. Please stay at a safe distance and avoid inhaling the smoke.",
    type: "message",
  },
  {
    messageId: 16,
    time: new Date("2024-11-30T14:36:00"),
    speaker: null,
    text: "Sirens approaching the area",
    type: "event",
  },
  {
    messageId: 17,
    time: new Date("2024-11-30T14:36:05"),
    speaker: "caller",
    text: "Okay, I’ll stay across the street. Is there anything else I should do?",
    type: "message",
  },
  {
    messageId: 18,
    time: new Date("2024-11-30T14:36:10"),
    speaker: "dispatcher",
    text: "Just remain calm and keep an eye out for the firefighters. If you notice anyone else exiting the building or needing assistance, inform them to come to a safe area.",
    type: "message",
  },
  {
    messageId: 19,
    time: new Date("2024-11-30T14:36:15"),
    speaker: null,
    text: "Children crying detected nearby",
    type: "event",
  },
  {
    messageId: 20,
    time: new Date("2024-11-30T14:36:20"),
    speaker: "caller",
    text: "There are a few cars parked in front of the hydrant. Should I try to get the owners to move them?",
    type: "message",
  },
  {
    messageId: 21,
    time: new Date("2024-11-30T14:36:25"),
    speaker: "dispatcher",
    text: "No, don’t risk your safety. The firefighters are trained to handle such situations. Just make sure you stay safe and away from the building.",
    type: "message",
  },
  {
    messageId: 22,
    time: new Date("2024-11-30T14:36:30"),
    speaker: null,
    text: "Fire truck has arrived",
    type: "event",
  },
  {
    messageId: 23,
    time: new Date("2024-11-30T14:36:35"),
    speaker: "caller",
    text: "I can see the fire truck now. Thank you for all the help!",
    type: "message",
  },
  {
    messageId: 24,
    time: new Date("2024-11-30T14:36:40"),
    speaker: "dispatcher",
    text: "You're welcome. Stay safe, and let the firefighters do their job. If you notice anything else important, call us back.",
    type: "message",
  },
  {
    messageId: 25,
    time: new Date("2024-11-30T14:36:45"),
    speaker: "caller",
    text: "Will do. Goodbye.",
    type: "message",
  },
];
